// layout.tsc
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header"; // Same folder import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Fallback in case metadata is not applied */}
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" href="/Favicon.png" type="image/png" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Header is now fixed at the top (from header.tsx styles) */}
        <Header logoUrl="/logo.png" />
        {/* Add top margin so content is not hidden under the fixed header */}
        <main style={{ marginTop: "80px" }}>{children}</main>
      </body>
    </html>
  );
}
